### ISSUE TITLE
Cannot load S-parameter file

### ISSUE THREAD

**Issue by dghan0219** [capn-freako/PyBERT#52]
Using Anaconda3 2019.07 (64-bit) and PyBERT 3.1.1, opening a channel description file (S-parameters, pulse, or impulse) produces a save window rather than an open window.  Hence, the file cannot be loaded.

**Comment by dghan0219** [comment]
...Hence the file cannot be loaded with the GUI.  Typing the full path to the file works and PyBERT runs with it, but relative paths to the file do not work and PyBERT cannot find it, although it can be hard to tell in which folder PyBERT thinks it is and that may be the problem.

**Comment by jdpatt** [comment]
The traits module is still weird to me.  This also affects the tx and rx's ami/dll file open dialogs.  They say "save" but I still think they correctly return a file path.  

A lot of paths were originally done using os.path, we should continue to move to pathlib so that it doesn't matter relative or full.

**Comment by dghan0219** [comment]
If I pick a channel description file and then click Save, I then get an overwrite confirmation, so it is not operating correctly in that case.  I have not tried the other dialogs except for the configuration buttons.
