### ISSUE TITLE
PyBERT 3.3.0 Configuration File Problems

### ISSUE THREAD

**Issue by dghan0219** [capn-freako/PyBERT#77]
This may be intentional, but configuration files saved with earlier versions of PyBERT are not being loaded by version 3.3.0.

IBIS models used are not being saved as part of the configuration (AMI and DLL files used are being saved).

**Comment by jdpatt** [comment]
The configuration format change is intentional.  It's now a human readable format instead of a pickled object.  So you can now make changes from any text editor without having pybert open or copy configurations with slight edits.  I imagine the new IBIS feature was just not added to the configuration yet.
